all:
  hosts:
    orchestrator:
      ansible_host: localhost
      ansible_connection: local
      ansible_user: labadmin
    maas:
      ansible_host: 10.0.1.253
      ansible_connection: local
      ansible_user: root
